pr: none

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build -d'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    jdkVersionOption: 1.11
  displayName: 'gradle build -d'
