trigger: none

pr:
- master
- release

# Different users have different machine setups, we run the build three times, on ubuntu, osx, and windows
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  currentImage: $(imageName)
  
steps: 
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx8192m'
    jdkArchitectureOption: 'x64'
    tasks: 'build --debug'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    jdkVersionOption: 1.17
  displayName: 'gradle build'
