package constants

const val VALIDATION_ENDPOINT = "validate"
const val HL7_VALIDATION_ENDPOINT = "%24validate"
const val RESOURCE_VALIDATION_ENDPOINT = "*/%24validate"
const val ID_VALIDATION_ENDPOINT = "*/*/%24validate"
const val DEFAULT_SESSION_ENDPOINT = "/defaultIg"
const val VALIDATOR_VERSION_ENDPOINT = "validator/version"
const val CONTEXT_ENDPOINT = "context"
const val IG_ENDPOINT = "ig"
const val IG_VERSIONS_ENDPOINT = "igVersions"
const val VERSIONS_ENDPOINT = "versions"
const val TERMINOLOGY_ENDPOINT = "terminology"
const val TX_SERVER_STATUS_ENDPOINT = "txStatus"
const val PACKAGES_SERVER_STATUS_ENDPOINT = "packStatus"
const val DEBUG_ENDPOINT = "debug"